version: 0.2
phases:
  pre_build:
    commands:
      - cd Web.Client/client
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
